// Builds src/data/tutorial.ts: the Rookie Ring's ideal line, how much of it is
// drawn for the player, and where the final corner sits (for coaching tips).
// The server checks every tutorial submission starts with exactly this line,
// so its leaderboard is about the last corner only.
//
//   npm run tracks:build   (runs this after scripts/build-tracks.ts)

import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CATALOG } from '../src/data/catalog.js';
import { encodePath, validatePath, decodePath } from '../src/sim/path.js';
import { buildTrack } from '../src/sim/track.js';
import { minCurvatureOffsets } from './optimal.js';

/** The player takes over this far before the final corner (metres). */
const RUN_IN = 110;

const meta = CATALOG.find((m) => m.tutorial);
if (!meta) throw new Error('no tutorial circuit in the catalog');
const geom = (await import(`../src/data/geometry/${meta.slug}.ts`)).default as number[];
const track = buildTrack(meta, geom);
const step = track.length / track.n;
const alpha = minCurvatureOffsets(track);

// The final corner: the last run of real curvature before the line. Heading
// change is measured across +-12 m so decimetre rounding noise stays out.
const turnAt = (i: number) => {
  const a = (i - 6 + track.n) % track.n, c = (i + 6) % track.n;
  const abx = track.x[i] - track.x[a], aby = track.y[i] - track.y[a];
  const bcx = track.x[c] - track.x[i], bcy = track.y[c] - track.y[i];
  return Math.abs(Math.atan2(abx * bcy - aby * bcx, abx * bcx + aby * bcy));
};
const bent = (i: number) => turnAt(i) > 0.08;
let out = track.n - 1;
while (out > 0 && !bent(out)) out--;
let inn = out;
while (inn > 0 && bent(inn - 1)) inn--;
let apex = inn;
for (let i = inn; i <= out; i++) if (turnAt(i) > turnAt(apex)) apex = i;
const cornerIn = inn * step, cornerOut = out * step;
// The apex of a long constant-radius corner is its middle.
const apexS = Math.abs(turnAt(apex) - turnAt(Math.round((inn + out) / 2))) < 0.01 ? ((inn + out) / 2) * step : apex * step;
const handoff = cornerIn - RUN_IN;

// The ideal line, point by point, noting how many points come before the handoff.
const pts: number[] = [];
let prefixPoints = 0;
let lx = Infinity, ly = Infinity;
for (let i = 0; i < track.n; i++) {
  const x = track.x[i] + alpha[i] * track.nx[i];
  const y = track.y[i] + alpha[i] * track.ny[i];
  if (i > 0 && Math.hypot(x - lx, y - ly) < 0.7) continue;
  pts.push(Math.round(x * 10), Math.round(y * 10));
  lx = x; ly = y;
  if (i * step <= handoff) prefixPoints = pts.length / 2;
}
pts.push(pts[0], pts[1]);
const line = encodePath(pts);
const check = validatePath(track, decodePath(line));
if (!check.ok) throw new Error(`tutorial ideal line is not legal: ${check.error}`);

writeFileSync(
  join(import.meta.dirname, '..', 'src', 'data', 'tutorial.ts'),
  '// Generated by scripts/build-tutorial.ts. Do not edit by hand.\n' +
    '// The tutorial circuit, its ideal line, and the part of it drawn for the player.\n\n' +
    'export const TUTORIAL = {\n' +
    `  slug: '${meta.slug}',\n` +
    '  /** Lap distance (m) where the line drawn for the player ends and theirs begins. */\n' +
    `  handoff: ${Math.round(handoff)},\n` +
    '  /** The final corner: where it starts, its apex and where it ends (lap metres). */\n' +
    `  cornerIn: ${Math.round(cornerIn)},\n  apex: ${Math.round(apexS)},\n  cornerOut: ${Math.round(cornerOut)},\n` +
    '  /** How many points of `line` are pre-drawn. */\n' +
    `  prefixPoints: ${prefixPoints},\n` +
    '  /** The ideal line as decimetre delta code: [x0, y0, dx1, dy1, ...]. */\n' +
    `  line: [${line.join(',')}],\n` +
    '};\n',
);
console.log(`tutorial: ${meta.slug} handoff ${Math.round(handoff)} m, corner ${Math.round(cornerIn)}-${Math.round(cornerOut)} m (apex ${Math.round(apexS)}), ${prefixPoints} of ${pts.length / 2} points pre-drawn`);
