// Generated by scripts/build-tracks.ts. Do not edit by hand. Server use only.
import g_rookie_ring from './geometry/rookie-ring.js';
import g_melbourne from './geometry/melbourne.js';
import g_shanghai from './geometry/shanghai.js';
import g_suzuka from './geometry/suzuka.js';
import g_bahrain from './geometry/bahrain.js';
import g_jeddah from './geometry/jeddah.js';
import g_miami from './geometry/miami.js';
import g_imola from './geometry/imola.js';
import g_monaco from './geometry/monaco.js';
import g_barcelona from './geometry/barcelona.js';
import g_montreal from './geometry/montreal.js';
import g_spielberg from './geometry/spielberg.js';
import g_silverstone from './geometry/silverstone.js';
import g_spa from './geometry/spa.js';
import g_hungaroring from './geometry/hungaroring.js';
import g_zandvoort from './geometry/zandvoort.js';
import g_monza from './geometry/monza.js';
import g_baku from './geometry/baku.js';
import g_singapore from './geometry/singapore.js';
import g_austin from './geometry/austin.js';
import g_mexico_city from './geometry/mexico-city.js';
import g_interlagos from './geometry/interlagos.js';
import g_las_vegas from './geometry/las-vegas.js';
import g_lusail from './geometry/lusail.js';
import g_yas_marina from './geometry/yas-marina.js';

export const GEOMETRY: Record<string, number[]> = {
  'rookie-ring': g_rookie_ring,
  'melbourne': g_melbourne,
  'shanghai': g_shanghai,
  'suzuka': g_suzuka,
  'bahrain': g_bahrain,
  'jeddah': g_jeddah,
  'miami': g_miami,
  'imola': g_imola,
  'monaco': g_monaco,
  'barcelona': g_barcelona,
  'montreal': g_montreal,
  'spielberg': g_spielberg,
  'silverstone': g_silverstone,
  'spa': g_spa,
  'hungaroring': g_hungaroring,
  'zandvoort': g_zandvoort,
  'monza': g_monza,
  'baku': g_baku,
  'singapore': g_singapore,
  'austin': g_austin,
  'mexico-city': g_mexico_city,
  'interlagos': g_interlagos,
  'las-vegas': g_las_vegas,
  'lusail': g_lusail,
  'yas-marina': g_yas_marina,
};
